### ISSUE TITLE
initial render

### ISSUE THREAD

**Issue by queckezz** [ahdinosaur/inu#1]
Hey man, `inu` looked so awesome, I had to try it out.

First thing I did is ran the `clock` example. I noticed that it'll only render html when one effect has been run. I simplified the example to show that the initial rendering is not working here: http://www.webpackbin.com/EJfHLOWMZ

Am I responsible for the first render by myself?
```js
html.update(main, app.view(app.init()))
```

Looking at [./start.js#L77](https://github.com/ahdinosaur/inu/blob/master/start.js#L77) it seems you've built that in so I'm unsure whats going on.

**Comment by ahdinosaur** [comment]
hey @queckezz, awesome glad it passed the intuition test, thanks for giving it a play.

> Am I responsible for the first render by myself?

nah, this is a bug. fixed in https://github.com/ahdinosaur/inu/commit/5f01b8b4c8d3a5883a2fd21cadacd679fa9c724b and published as [`v2.2.2`](https://github.com/ahdinosaur/inu/releases/tag/v2.2.2).

turns out, because of [how `pull-notify` works](https://github.com/pull-stream/pull-notify/blob/master/index.js), it's necessary to listen to the stream before you can receive the events (otherwise the streams would have to keep all past events because of [how `pull-pushable` works](https://github.com/pull-stream/pull-pushable/blob/master/index.js)), but the events were being triggered before the user could listen. i've changed this so that the initial state is sent on next tick, so you have until then to start listening.

thanks again for this bug report, close if you confirm the fix works.

**Comment by ahdinosaur** [comment]
by the way @queckezz, i changed your example when testing as well, see [here](http://www.webpackbin.com/EkH6fUzGb):

```js
const { html, pull, start } = require('inu')
const delay = require('pull-delay')

// minimal demo
const app = {
  init: () => ({ model: 'kittens' }),
  update: (model, action) => ({ model }),
  view: (model, dispatch) => html`
    <div>${model}</div>
  `
}

const main = document.getElementById('app')
const { views } = start(app)

pull(
  views(),
  pull.drain(function (view) {
    html.update(main, view)
  })
)
```

changes:

- view can return anything, but if using with `inu.html` i recommend reading the [`yo-yo`](https://github.com/maxogden/yo-yo) docs. in this case, [`html` is a function that is given template strings and returns DOM elements](https://github.com/maxogden/yo-yo#yotemplate). [`html.update` is a function that is given a target DOM element and a source DOM element and morphs the target with properties of the source](https://github.com/maxogden/yo-yo#youpdatetargetelement-newelement). i guess the `inu` docs are missing a direct link, oops.
- used `<div>` instead of `<span>`, because (should probably document this) when using `html.update` the source element needs to be the same tag type as the target element. in this case `#app` is a `<div>`, so `view` should return the same.
- model is `"kittens"` instead of `0`, because why not.
- added an empty `update`, because it should break without one. do you think i should make `update` be optional and use this default when `update` is not given?

churrrrrrrr

**Comment by ahdinosaur** [comment]
@pietgeursen, eyyy you wanna write a test for this bug? :cookie:

**Comment by pietgeursen** [comment]
yep :)

**Comment by queckezz** [comment]
Ah, thanks for the thorough explanation and the fast fix! That makes total sense.

> view can return anything, but if using with inu.html i recommend reading the yo-yo docs. in this case, html is a function that is given template strings and returns DOM elements. html.update is a function that is given a target DOM element and a source DOM element and morphs the target with properties of the source. i guess the inu docs are missing a direct link, oops.

Right, I changed it to a plain string because it broke webpackbin's syntax highlighting for some wierd reason. But you're right I forgot to add `yo-yo`'s `html()`

> added an empty update, because it should break without one. do you think i should make update be optional and use this default when update is not given?

I think its a valid use case to have some static initial state like say a `title` that you want to reuse across the component. On the other side this is no different and has no additional benefit from just doing

```js
const title = 'A title'

const subComponent = () => html`<p>${title}</p>`

// or pass it down

const subComponent = (title) => html`<p>${title}</p>`
```

I'll try out `inu` for some smaller project and report back to see how it goes :+1:
